(define (square x) (* x x))
(define (fact n)
  (if (= n 0) 1 (* n (fact (- n 1)))))
(define (sum-to n)
  (let loop ((i 0) (acc 0))
    (if (> i n) acc (loop (+ i 1) (+ acc i)))))
(display (square 7)) (newline)
(display (fact 10)) (newline)
(display (sum-to 100)) (newline)
