#!/usr/bin/env python3
"""Generate Coil tables for Unicode extended grapheme segmentation.

Data comes from the versioned UCD URLs below. The generated module is checked in so
normal Coil builds never require Python or network access.
"""

from __future__ import annotations

import re
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "src/stdlib/unicode_grapheme_data.coil"
TEST_OUT = ROOT / "tests/unicode_grapheme_conformance_test.coil"
UCD_VERSION = "17.0.0"
BASE = f"https://www.unicode.org/Public/{UCD_VERSION}/ucd"
SOURCES = {
    "gcb": f"{BASE}/auxiliary/GraphemeBreakProperty.txt",
    "emoji": f"{BASE}/emoji/emoji-data.txt",
    "derived": f"{BASE}/DerivedCoreProperties.txt",
    "tests": f"{BASE}/auxiliary/GraphemeBreakTest.txt",
}

LINE = re.compile(r"^([0-9A-F]+)(?:\.\.([0-9A-F]+))?\s*;\s*([^\s#]+)")


def fetch(url: str) -> str:
    with urllib.request.urlopen(url) as response:
        return response.read().decode("utf-8")


def ranges(text: str, wanted: set[str]) -> list[tuple[int, int, str]]:
    result: list[tuple[int, int, str]] = []
    for line in text.splitlines():
        match = LINE.match(line)
        if not match or match.group(3) not in wanted:
            continue
        lo = int(match.group(1), 16)
        hi = int(match.group(2) or match.group(1), 16)
        result.append((lo, hi, match.group(3)))
    result.sort()
    return result


def decision_tree(items: list[tuple[int, int, int]], default: int, indent: int = 2) -> str:
    pad = " " * indent
    if not items:
        return f"{pad}{default}"
    if len(items) == 1:
        lo, hi, value = items[0]
        if lo == hi:
            return f"{pad}(if (= cp (cast i64 {lo})) {value} {default})"
        return f"{pad}(if (and (>= cp (cast i64 {lo})) (<= cp (cast i64 {hi}))) {value} {default})"
    middle = len(items) // 2
    pivot = items[middle][0]
    left = decision_tree(items[:middle], default, indent + 2)
    right = decision_tree(items[middle:], default, indent + 2)
    return f"{pad}(if (< cp (cast i64 {pivot}))\n{left}\n{right})"


def emit_function(name: str, items: list[tuple[int, int, int]], default: int) -> str:
    body = decision_tree(items, default, 2)
    return f"(defn {name} [(value u32)] (-> i64)\n  (let [cp (primitive/cast i64 value)]\n{body}))\n"


def emit_conformance_tests(text: str) -> tuple[str, int]:
    cases: list[str] = []
    for raw_line in text.splitlines():
        line = raw_line.split("#", 1)[0].strip()
        if not line:
            continue
        tokens = line.split()
        codepoints: list[int] = []
        boundaries: list[int] = []
        byte_offset = 0
        marker = tokens[0]
        if marker == "÷":
            boundaries.append(0)
        for index in range(1, len(tokens), 2):
            cp = int(tokens[index], 16)
            codepoints.append(cp)
            byte_offset += len(chr(cp).encode("utf-8"))
            marker = tokens[index + 1]
            if marker == "÷":
                boundaries.append(byte_offset)
        escaped = "".join(f"\\x{cp:x};" for cp in codepoints)
        ends = " ".join(str(offset) for offset in boundaries[1:])
        cases.append(f'    (check-case "{escaped}" [{ends}])')

    source = """(module coil.tests.unicode-grapheme-conformance)
(import "coil.assert" :use *)
(import "coil.slice" :use [slice-get slice-len])
(import "coil.str" :as string)
(import "coil.unicode.grapheme" :as grapheme)
; GENERATED by scripts/docs/gen-grapheme-data.py from Unicode GraphemeBreakTest.

(defn check-case [(bytes (slice u8)) (ends (slice i64))] (-> i64)
  (let [text (string/string-view-unchecked bytes)
        (mut iterator) (iter (grapheme/chars text))
        (mut offset) 0
        (mut index) 0]
    (loop
      (match (next (mut iterator))
        (None [] (break))
        (Some [char]
          (do
            (store! offset
                    (+ (load offset)
                       (string/string-view-byte-len (grapheme/char-view char))))
            (assert (< (load index) (slice-len ends)))
            (assert-eq (load offset) (slice-get ends (load index)))
            (store! index (+ (load index) 1))))))
    (assert-eq (load index) (slice-len ends))
    0))

(deftest unicode-grapheme-break-conformance
""" + "\n".join(cases) + "\n  0)\n"
    return source, len(cases)


def main() -> None:
    raw = {name: fetch(url) for name, url in SOURCES.items()}
    gcb_names = ["CR", "LF", "Control", "Extend", "ZWJ", "Regional_Indicator",
                 "Prepend", "SpacingMark", "L", "V", "T", "LV", "LVT"]
    gcb_codes = {name: index + 1 for index, name in enumerate(gcb_names)}
    gcb = [(lo, hi, gcb_codes[name])
           for lo, hi, name in ranges(raw["gcb"], set(gcb_names))]
    emoji = [(lo, hi, 1)
             for lo, hi, _ in ranges(raw["emoji"], {"Extended_Pictographic"})]

    # DerivedCoreProperties encodes these as `InCB; Linker`, so parse the second
    # property field separately instead of using the generic one-field parser.
    incb: list[tuple[int, int, int]] = []
    incb_codes = {"Consonant": 1, "Extend": 2, "Linker": 3}
    incb_line = re.compile(
        r"^([0-9A-F]+)(?:\.\.([0-9A-F]+))?\s*;\s*InCB\s*;\s*(Consonant|Extend|Linker)")
    for line in raw["derived"].splitlines():
        match = incb_line.match(line)
        if match:
            incb.append((int(match.group(1), 16),
                         int(match.group(2) or match.group(1), 16),
                         incb_codes[match.group(3)]))
    incb.sort()

    header = f"""(module coil.unicode.grapheme-data)
(import "coil.primitive" :as primitive)
; GENERATED by scripts/docs/gen-grapheme-data.py from Unicode {UCD_VERSION}.
; Do not edit by hand. Property codes are private to coil.unicode.grapheme.
; Unicode data license: docs/maintenance/UNICODE_LICENSE.md.

"""
    output = header
    output += emit_function("grapheme-break-property", gcb, 0) + "\n"
    output += emit_function("extended-pictographic?", emoji, 0) + "\n"
    output += emit_function("indic-conjunct-break-property", incb, 0)
    OUT.write_text(output)
    tests, case_count = emit_conformance_tests(raw["tests"])
    TEST_OUT.write_text(tests)
    print(f"wrote {OUT.relative_to(ROOT)} ({len(gcb)} GCB, {len(emoji)} EP, {len(incb)} InCB ranges)")
    print(f"wrote {TEST_OUT.relative_to(ROOT)} ({case_count} conformance cases)")


if __name__ == "__main__":
    main()
