[package]
name = "compiler"
entry = "main.coil"
source-roots = ["."]
exclude = ["./prelude.coil", "./metashim.coil", "./metashim_wasm.coil", "./formatter/sample.coil"]

[native-dependencies]
llvm = { flags-command = "llvm-config --ldflags --libs --system-libs" }
